CREATE TABLE "hit" (
    tenant_id UInt64 NULL,
    fingerprint FixedString(32),
    time DateTime('UTC'),
    session DateTime('UTC') NULL,
    user_agent String,
    path String,
    url String,
    language String NULL,
    country_code FixedString(2) NULL,
    referrer String NULL,
    referrer_name String NULL,
    referrer_icon String NULL,
    os String NULL,
    os_version String NULL,
    browser String NULL,
    browser_version String NULL,
    desktop Boolean DEFAULT 0,
    mobile Boolean DEFAULT 0,
    screen_width UInt16 DEFAULT 0,
    screen_height UInt16 DEFAULT 0,
    screen_class String NULL,
    utm_source String NULL,
    utm_medium String NULL,
    utm_campaign String NULL,
    utm_content String NULL,
    utm_term String NULL
) ENGINE = MergeTree()
PARTITION BY toYYYYMMDD(time)
ORDER BY (time);
