RENAME TABLE session TO session_backup;
RENAME TABLE page_view TO page_view_backup;
RENAME TABLE event TO event_backup;

CREATE TABLE session
(
    `sign` Int8,
    `client_id` UInt64,
    `visitor_id` UInt64,
    `session_id` UInt32,
    `time` DateTime64(3, 'UTC'),
    `start` DateTime64(3, 'UTC'),
    `duration_seconds` UInt32,
    `entry_title` String,
    `is_bounce` UInt8,
    `entry_path` String,
    `exit_path` String,
    `page_views` UInt16,
    `language` LowCardinality(String),
    `country_code` LowCardinality(FixedString(2)),
    `city` String,
    `referrer` String,
    `referrer_name` String,
    `referrer_icon` String,
    `os` LowCardinality(String),
    `os_version` LowCardinality(String),
    `browser` LowCardinality(String),
    `browser_version` LowCardinality(String),
    `desktop` Int8,
    `mobile` Int8,
    `screen_width` UInt16,
    `screen_height` UInt16,
    `screen_class` LowCardinality(String),
    `utm_source` String,
    `utm_medium` String,
    `utm_campaign` String,
    `utm_content` String,
    `utm_term` String,
    `exit_title` String
)
ENGINE = CollapsingMergeTree(sign)
PARTITION BY toYYYYMM(time)
ORDER BY (client_id, visitor_id, session_id, time)
SETTINGS index_granularity = 8192
;

CREATE TABLE page_view
(
    `client_id` UInt64,
    `visitor_id` UInt64,
    `session_id` UInt32 DEFAULT 0,
    `time` DateTime64(3, 'UTC'),
    `duration_seconds` UInt32 DEFAULT 0,
    `path` String,
    `title` String,
    `language` LowCardinality(String),
    `country_code` LowCardinality(FixedString(2)),
    `city` String,
    `referrer` String DEFAULT '',
    `referrer_name` String DEFAULT '',
    `referrer_icon` String DEFAULT '',
    `os` LowCardinality(String),
    `os_version` LowCardinality(String),
    `browser` LowCardinality(String),
    `browser_version` LowCardinality(String),
    `desktop` Int8 DEFAULT 0,
    `mobile` Int8 DEFAULT 0,
    `screen_width` UInt16 DEFAULT 0,
    `screen_height` UInt16 DEFAULT 0,
    `screen_class` LowCardinality(String),
    `utm_source` String DEFAULT '',
    `utm_medium` String DEFAULT '',
    `utm_campaign` String DEFAULT '',
    `utm_content` String DEFAULT '',
    `utm_term` String DEFAULT ''
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(time)
ORDER BY (client_id, visitor_id, session_id, time)
SETTINGS index_granularity = 8192
;

CREATE TABLE event
(
    `client_id` UInt64,
    `time` DateTime64(3, 'UTC'),
    `duration_seconds` UInt32 DEFAULT 0,
    `path` String,
    `language` LowCardinality(String),
    `country_code` LowCardinality(FixedString(2)),
    `referrer` String,
    `referrer_name` String,
    `referrer_icon` String,
    `os` LowCardinality(String),
    `os_version` LowCardinality(String),
    `browser` LowCardinality(String),
    `browser_version` LowCardinality(String),
    `desktop` Int8 DEFAULT 0,
    `mobile` Int8 DEFAULT 0,
    `screen_width` UInt16 DEFAULT 0,
    `screen_height` UInt16 DEFAULT 0,
    `screen_class` LowCardinality(String),
    `utm_source` String,
    `utm_medium` String,
    `utm_campaign` String,
    `utm_content` String,
    `utm_term` String,
    `event_name` String,
    `event_meta_keys` Array(String),
    `event_meta_values` Array(String),
    `title` String,
    `session_id` UInt32 DEFAULT 0,
    `city` String,
    `visitor_id` UInt64
)
ENGINE = MergeTree
PARTITION BY toYYYYMM(time)
ORDER BY (client_id, time)
SETTINGS index_granularity = 8192
;

INSERT INTO session (
    `sign`,
    `client_id`,
    `visitor_id`,
    `session_id`,
    `time`,
    `start`,
    `duration_seconds`,
    `entry_title`,
    `is_bounce`,
    `entry_path`,
    `exit_path`,
    `page_views`,
    `language`,
    `country_code`,
    `city`,
    `referrer`,
    `referrer_name`,
    `referrer_icon`,
    `os`,
    `os_version`,
    `browser`,
    `browser_version`,
    `desktop`,
    `mobile`,
    `screen_width`,
    `screen_height`,
    `screen_class`,
    `utm_source`,
    `utm_medium`,
    `utm_campaign`,
    `utm_content`,
    `utm_term`,
    `exit_title`
)
SELECT `sign`,
`client_id`,
`visitor_id`,
`session_id`,
`time`,
`start`,
`duration_seconds`,
`entry_title`,
`is_bounce`,
`entry_path`,
`exit_path`,
`page_views`,
`language`,
`country_code`,
`city`,
`referrer`,
`referrer_name`,
`referrer_icon`,
`os`,
`os_version`,
`browser`,
`browser_version`,
`desktop`,
`mobile`,
`screen_width`,
`screen_height`,
`screen_class`,
`utm_source`,
`utm_medium`,
`utm_campaign`,
`utm_content`,
`utm_term`,
`exit_title`
FROM session_backup
;

INSERT INTO page_view (
    `client_id`,
    `visitor_id`,
    `session_id`,
    `time`,
    `duration_seconds`,
    `path`,
    `title`,
    `language`,
    `country_code`,
    `city`,
    `referrer`,
    `referrer_name`,
    `referrer_icon`,
    `os`,
    `os_version`,
    `browser`,
    `browser_version`,
    `desktop`,
    `mobile`,
    `screen_width`,
    `screen_height`,
    `screen_class`,
    `utm_source`,
    `utm_medium`,
    `utm_campaign`,
    `utm_content`,
    `utm_term`
)
SELECT `client_id`,
`visitor_id`,
`session_id`,
`time`,
`duration_seconds`,
`path`,
`title`,
`language`,
`country_code`,
`city`,
`referrer`,
`referrer_name`,
`referrer_icon`,
`os`,
`os_version`,
`browser`,
`browser_version`,
`desktop`,
`mobile`,
`screen_width`,
`screen_height`,
`screen_class`,
`utm_source`,
`utm_medium`,
`utm_campaign`,
`utm_content`,
`utm_term`
FROM page_view_backup
;

INSERT INTO event (
    `client_id`,
    `time`,
    `duration_seconds`,
    `path`,
    `language`,
    `country_code`,
    `referrer`,
    `referrer_name`,
    `referrer_icon`,
    `os`,
    `os_version`,
    `browser`,
    `browser_version`,
    `desktop`,
    `mobile`,
    `screen_width`,
    `screen_height`,
    `screen_class`,
    `utm_source`,
    `utm_medium`,
    `utm_campaign`,
    `utm_content`,
    `utm_term`,
    `event_name`,
    `event_meta_keys`,
    `event_meta_values`,
    `title`,
    `session_id`,
    `city`,
    `visitor_id`
)
SELECT `client_id`,
`time`,
`duration_seconds`,
`path`,
`language`,
`country_code`,
`referrer`,
`referrer_name`,
`referrer_icon`,
`os`,
`os_version`,
`browser`,
`browser_version`,
`desktop`,
`mobile`,
`screen_width`,
`screen_height`,
`screen_class`,
`utm_source`,
`utm_medium`,
`utm_campaign`,
`utm_content`,
`utm_term`,
`event_name`,
`event_meta_keys`,
`event_meta_values`,
`title`,
`session_id`,
`city`,
`visitor_id`
FROM event_backup
;
